### ISSUE TITLE
Vulnerabilites found running your docker image

### ISSUE THREAD

**Issue by advapiIT** [juanluisbaptiste/docker-otrs#89]
Hello,
Before using your docker container, I've been asked to check with Anchore if there were high vulnerability rate in your docker image and running it today I've found those:
[vulns.txt](https://github.com/juanluisbaptiste/docker-otrs/files/4475246/vulns.txt)
[details.txt](https://github.com/juanluisbaptiste/docker-otrs/files/4475247/details.txt)

Considering this, it's safe to use this docker image in production environment? do you think you can apply some patches? Thanks in advance

**Comment by juanluisbaptiste** [comment]
Hi,

You are more than welcome to fix them, I don't have the time to do it.

**Comment by juanluisbaptiste** [comment]
As vulnerabilities come from the base CentOS 7 image which is the officially supported OS for OTRS 6 this will not be fixed because migrating to CentOS 8 is not an easy task and will make this container harder to support upstream.

Until upstream changes this base requirement it will not be changed here neither, closing this as wont fix.
